
title: Sudershan Pothina 
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Currently working as a Senior DevOps Enginner 
  <br><br>
  <a href="https://www.linkedin.com/in/sudershan-pothina-165650205/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal