
title: Sudershan Pothina 
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  DevSecOps Engineer
  <br><br>
  Aspiring DevOps Architect
  <br><br>
  Experience in Ansible, Azure, Azure DevOps, Docker, Dynatrace, Elastic Search, Gitlab, Golang, Java, Jenkins, Kafka, Kubernetes, SonarQube, Terraform, UrbanCode Deploy
  <br><br>
  <a href="https://www.credly.com/users/sudershan-pothina.3f0f7dbe/badges">Credly</a>
  <br><br>
  <a href="https://www.linkedin.com/in/sudershan-pothina-165650205/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
